"""
Workspace structure API contracts.

Responsibilities:
- Centralize request and response field names for workspace structure creation.
- Keep transport contract strings out of route and service logic.
"""

WORKSPACE_STRUCTURE_REQUEST_BASE_PATH = "basePath"
WORKSPACE_STRUCTURE_REQUEST_FOLDERS = "folders"
WORKSPACE_STRUCTURE_REQUEST_FILES = "files"
WORKSPACE_STRUCTURE_REQUEST_FILE_PATH = "path"
WORKSPACE_STRUCTURE_REQUEST_FILE_CONTENT = "content"
WORKSPACE_STRUCTURE_REQUEST_OVERWRITE_FILES = "overwriteFiles"

WORKSPACE_STRUCTURE_RESPONSE_SUCCESS = "success"
WORKSPACE_STRUCTURE_RESPONSE_CREATED_FOLDERS = "createdFolders"
WORKSPACE_STRUCTURE_RESPONSE_CREATED_FILES = "createdFiles"
WORKSPACE_STRUCTURE_RESPONSE_SKIPPED_FILES = "skippedFiles"
WORKSPACE_STRUCTURE_RESPONSE_ERRORS = "errors"
WORKSPACE_STRUCTURE_RESPONSE_CREATED_FOLDER_PATHS = "createdFolderPaths"
WORKSPACE_STRUCTURE_RESPONSE_CREATED_FILE_PATHS = "createdFilePaths"
WORKSPACE_STRUCTURE_RESPONSE_SKIPPED_FILE_PATHS = "skippedFilePaths"
