REQUEST_TIMEOUT_SECONDS = 30

HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POST"
HTTP_METHOD_PUT = "PUT"
HTTP_METHOD_DELETE = "DELETE"

ENDPOINT_TEST_CONFIG_FOLDER_NAME = "config"
ENDPOINT_TEST_CONFIG_FILE_NAME = "test_endpoints.json"

OUTPUT_FOLDER_NAME = "output"

ENDPOINT_TEST_SUMMARY_FILE_PREFIX = "endpoint_test_summary"

JSON_FILE_EXTENSION = ".json"
