"""Factory task runner tests."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from src.core.factory.task_execution_models import (
    FactoryTaskExecutionRequest,
    FactoryTaskExecutionResult,
)
from src.core.factory.task_artifact_writer import FactoryTaskArtifactWriter
from src.core.factory.task_models import FactoryTask
from src.core.factory.task_report_writer import FactoryTaskReportWriter
from src.core.factory.task_runner import FactoryTaskRunner
from src.core.factory.task_prompt_compiler import build_default_task_prompt_compiler
from src.core.factory.task_status import (
    TASK_STATUS_COMPLETED,
    TASK_STATUS_FAILED,
    TASK_STATUS_PENDING,
    TASK_STATUS_RUNNING,
)


@dataclass
class InMemoryTaskRepository:
    pending_tasks: tuple[FactoryTask, ...]
    initialized: bool = False
    running_task_ids: list[str] = field(default_factory=list)
    completed_task_ids: list[str] = field(default_factory=list)
    failed_tasks: dict[str, str] = field(default_factory=dict)

    def initialize_schema(self) -> None:
        self.initialized = True

    def find_pending_tasks(self) -> tuple[FactoryTask, ...]:
        return self.pending_tasks

    def upsert_task(self, task: FactoryTask) -> None:
        raise NotImplementedError

    def mark_running(self, task_id: str) -> None:
        self.running_task_ids.append(task_id)

    def mark_completed(self, task_id: str) -> None:
        self.completed_task_ids.append(task_id)

    def mark_failed(self, task_id: str, error_message: str) -> None:
        self.failed_tasks[task_id] = error_message


@dataclass
class PassingExecutionProvider:
    requests: list[FactoryTaskExecutionRequest] = field(default_factory=list)

    def execute(self, request: FactoryTaskExecutionRequest) -> FactoryTaskExecutionResult:
        self.requests.append(request)
        return FactoryTaskExecutionResult(
            task_id=request.task_id,
            success=True,
            message="done",
            artifact_text="# Generated Artifact\n\nThis artifact was generated by the test provider.",
        )


@dataclass
class FailingExecutionProvider:
    def execute(self, request: FactoryTaskExecutionRequest) -> FactoryTaskExecutionResult:
        return FactoryTaskExecutionResult(
            task_id=request.task_id,
            success=False,
            message="failed",
        )


@dataclass
class RaisingExecutionProvider:
    def execute(self, request: FactoryTaskExecutionRequest) -> FactoryTaskExecutionResult:
        raise RuntimeError("provider boom")


def build_task(payload: str = '{"scope": "test"}') -> FactoryTask:
    return FactoryTask(
        task_id="factory.example",
        name="Example Task",
        description="Example pending task.",
        status=TASK_STATUS_PENDING,
        task_definition_path="backend/src/core/factory/tasks/example.json",
        priority=10,
        payload=payload,
    )


def test_runner_executes_pending_task_and_marks_completed(tmp_path: Path) -> None:
    task = build_task()
    repository = InMemoryTaskRepository(pending_tasks=(task,))
    execution_provider = PassingExecutionProvider()

    result = FactoryTaskRunner(
        task_repository=repository,
        execution_provider=execution_provider,
        prompt_compiler=build_default_task_prompt_compiler(Path.cwd()),
        artifact_writer=FactoryTaskArtifactWriter(tmp_path / "output"),
        report_writer=FactoryTaskReportWriter(tmp_path / "reports"),
    ).run_pending_tasks()

    assert repository.initialized is True
    assert repository.running_task_ids == ["factory.example"]
    assert repository.completed_task_ids == ["factory.example"]
    assert repository.failed_tasks == {}
    assert execution_provider.requests[0].task_id == "factory.example"
    assert execution_provider.requests[0].payload == {"scope": "test"}
    result_dict = result.to_dict()
    assert result_dict["discovered_count"] == 1
    assert result_dict["executed_count"] == 1
    assert result_dict["completed_count"] == 1
    assert result_dict["failed_count"] == 0
    task_run = result_dict["task_runs"][0]
    assert task_run["task_id"] == "factory.example"
    assert task_run["name"] == "Example Task"
    assert task_run["status"] == TASK_STATUS_COMPLETED
    assert task_run["message"] == "done"
    assert "artifact_path" in task_run
    assert "report_path" in task_run


def test_runner_marks_failed_when_execution_provider_returns_failure(tmp_path: Path) -> None:
    task = build_task()
    repository = InMemoryTaskRepository(pending_tasks=(task,))

    result = FactoryTaskRunner(
        task_repository=repository,
        execution_provider=FailingExecutionProvider(),
        prompt_compiler=build_default_task_prompt_compiler(Path.cwd()),
        artifact_writer=FactoryTaskArtifactWriter(tmp_path / "output"),
        report_writer=FactoryTaskReportWriter(tmp_path / "reports"),
    ).run_pending_tasks()

    assert repository.running_task_ids == ["factory.example"]
    assert repository.completed_task_ids == []
    assert repository.failed_tasks == {"factory.example": "failed"}
    assert result.failed_count == 1


def test_runner_marks_failed_when_execution_provider_raises(tmp_path: Path) -> None:
    task = build_task()
    repository = InMemoryTaskRepository(pending_tasks=(task,))

    result = FactoryTaskRunner(
        task_repository=repository,
        execution_provider=RaisingExecutionProvider(),
        prompt_compiler=build_default_task_prompt_compiler(Path.cwd()),
        artifact_writer=FactoryTaskArtifactWriter(tmp_path / "output"),
        report_writer=FactoryTaskReportWriter(tmp_path / "reports"),
    ).run_pending_tasks()

    assert repository.running_task_ids == ["factory.example"]
    assert repository.completed_task_ids == []
    assert repository.failed_tasks == {"factory.example": "provider boom"}
    assert result.failed_count == 1


def test_runner_marks_failed_when_payload_is_invalid_json(tmp_path: Path) -> None:
    task = build_task(payload="not-json")
    repository = InMemoryTaskRepository(pending_tasks=(task,))
    execution_provider = PassingExecutionProvider()

    result = FactoryTaskRunner(
        task_repository=repository,
        execution_provider=execution_provider,
        prompt_compiler=build_default_task_prompt_compiler(Path.cwd()),
        artifact_writer=FactoryTaskArtifactWriter(tmp_path / "output"),
        report_writer=FactoryTaskReportWriter(tmp_path / "reports"),
    ).run_pending_tasks()

    assert repository.running_task_ids == []
    assert repository.completed_task_ids == []
    assert repository.failed_tasks == {"factory.example": "Invalid task payload JSON: Expecting value"}
    assert execution_provider.requests == []
    assert result.failed_count == 1
