"""Deterministic local LLM provider for offline Factory execution."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MockLlmProvider:
    """Offline provider used for local smoke tests and deterministic runs."""

    def generate_artifact(self, prompt: str, system_instruction: str | None = None) -> str:
        """Generate a deterministic artifact without calling an external service."""

        instruction_text = system_instruction or "No system instruction provided."
        return (
            "# CCore Factory Generated Artifact\n\n"
            "This artifact was generated by the local mock LLM provider.\n\n"
            "## System Instruction Preview\n\n"
            f"{instruction_text[:500]}\n\n"
            "## Prompt Preview\n\n"
            f"{prompt[:1200]}\n"
        )
