"""CCore pipeline repository protocols."""
from __future__ import annotations

from typing import Protocol

from backend.src.ccore.pipelines.pipeline import CCorePipeline, CCorePipelineStatus


class CCorePipelineRepositoryProtocol(Protocol):
    def find_all_pipelines(self) -> list[CCorePipeline]: ...
    def find_by_id(self, pipeline_id: str) -> CCorePipeline | None: ...
    def create_pipeline(self, pipeline: CCorePipeline) -> CCorePipeline: ...
    def update_pipeline(self, pipeline: CCorePipeline) -> CCorePipeline | None: ...
    def delete_pipeline(self, pipeline_id: str) -> bool: ...


class CCorePipelineStatusRepositoryProtocol(Protocol):
    def find_all_statuses(self) -> list[CCorePipelineStatus]: ...
    def find_status_by_id(self, pipeline_status_id: int) -> CCorePipelineStatus | None: ...
