STATUS_PASSED = "PASSED"
STATUS_FAILED = "FAILED"
STATUS_ERROR = "ERROR"
STATUS_SKIPPED = "SKIPPED"
STATUS_WARNING = "WARNING"

ENCODING_UTF_8 = "utf-8"
JSON_INDENT = 4

ROUTE_TYPE_EXACT = "exact"
ROUTE_TYPE_PREFIX = "prefix"

ROUTE_TYPE_KEYS = {
    ROUTE_TYPE_EXACT,
    ROUTE_TYPE_PREFIX,
}

OUTPUT_FOLDER_NAME = "output"
CONFIG_FOLDER_NAME = "config"
