"""
CCore task execution constants.

Responsibilities:
- Centralize CCore task execution table, column, status, and API field names.
- Avoid hardcoded execution contract strings across repositories, services, and routes.
"""

CCORE_TASK_EXECUTION_STATUSES_TABLE_NAME = "ccore_task_execution_statuses"
CCORE_TASK_EXECUTIONS_TABLE_NAME = "ccore_task_executions"

CCORE_TASK_EXECUTION_STATUS_CODE_COLUMN = "status_code"
CCORE_TASK_EXECUTION_STATUS_LABEL_COLUMN = "status_label"
CCORE_TASK_EXECUTION_STATUS_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_ID_COLUMN = "execution_id"
CCORE_TASK_EXECUTION_TASK_ID_COLUMN = "task_id"
CCORE_TASK_EXECUTION_RUNNER_CODE_COLUMN = "runner_code"
CCORE_TASK_EXECUTION_REPORT_JSON_COLUMN = "report_json"
CCORE_TASK_EXECUTION_STARTED_AT_COLUMN = "started_at"
CCORE_TASK_EXECUTION_FINISHED_AT_COLUMN = "finished_at"
CCORE_TASK_EXECUTION_CREATED_AT_COLUMN = "created_at"

CCORE_TASK_EXECUTION_STATUS_PENDING = "PENDING"
CCORE_TASK_EXECUTION_STATUS_RUNNING = "RUNNING"
CCORE_TASK_EXECUTION_STATUS_SUCCEEDED = "SUCCEEDED"
CCORE_TASK_EXECUTION_STATUS_FAILED = "FAILED"
CCORE_TASK_EXECUTION_STATUS_BLOCKED = "BLOCKED"

CCORE_TASK_RUNNER_VALIDATE_PROJECT = "validate-project"

CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_ID = "executionId"
CCORE_TASK_EXECUTION_API_FIELD_TASK_ID = "taskId"
CCORE_TASK_EXECUTION_API_FIELD_STATUS = "status"
CCORE_TASK_EXECUTION_API_FIELD_STATUS_LABEL = "statusLabel"
CCORE_TASK_EXECUTION_API_FIELD_RUNNER_CODE = "runnerCode"
CCORE_TASK_EXECUTION_API_FIELD_REPORT = "report"
CCORE_TASK_EXECUTION_API_FIELD_STARTED_AT = "startedAt"
CCORE_TASK_EXECUTION_API_FIELD_FINISHED_AT = "finishedAt"
CCORE_TASK_EXECUTION_API_FIELD_CREATED_AT = "createdAt"
