"""
CCore task execution constants.

Responsibilities:
- Centralize CCore task execution table, column, status, and API field names.
- Avoid hardcoded execution contract strings across repositories, services, and routes.
"""

CCORE_TASK_EXECUTION_STATUSES_TABLE_NAME = "ccore_task_execution_statuses"
CCORE_TASK_EXECUTIONS_TABLE_NAME = "ccore_task_executions"

CCORE_TASK_EXECUTION_STATUS_CODE_COLUMN = "status_code"
CCORE_TASK_EXECUTION_STATUS_LABEL_COLUMN = "status_label"
CCORE_TASK_EXECUTION_STATUS_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_ID_COLUMN = "execution_id"
CCORE_TASK_EXECUTION_TASK_ID_COLUMN = "task_id"
CCORE_TASK_EXECUTION_PROVIDER_PROFILE_COLUMN = "provider_profile"
CCORE_TASK_EXECUTION_MODE_COLUMN = "execution_mode"
CCORE_TASK_EXECUTION_REQUESTED_BY_COLUMN = "requested_by"
CCORE_TASK_EXECUTION_INPUT_PAYLOAD_COLUMN = "input_payload"
CCORE_TASK_EXECUTION_CONFIGURATION_SNAPSHOT_COLUMN = "configuration_snapshot"
CCORE_TASK_EXECUTION_VALIDATION_SNAPSHOT_COLUMN = "validation_snapshot"
CCORE_TASK_EXECUTION_REPORT_COLUMN = "execution_report"
CCORE_TASK_EXECUTION_ERROR_DETAILS_COLUMN = "error_details"
CCORE_TASK_EXECUTION_STARTED_AT_COLUMN = "started_at"
CCORE_TASK_EXECUTION_COMPLETED_AT_COLUMN = "completed_at"
CCORE_TASK_EXECUTION_FAILED_AT_COLUMN = "failed_at"
CCORE_TASK_EXECUTION_CREATED_AT_COLUMN = "created_at"
CCORE_TASK_EXECUTION_UPDATED_AT_COLUMN = "updated_at"

CCORE_TASK_EXECUTION_STATUS_PENDING = "PENDING"
CCORE_TASK_EXECUTION_STATUS_RUNNING = "RUNNING"
CCORE_TASK_EXECUTION_STATUS_COMPLETED = "COMPLETED"
CCORE_TASK_EXECUTION_STATUS_FAILED = "FAILED"
CCORE_TASK_EXECUTION_STATUS_BLOCKED = "BLOCKED"

#
# Existing runner identifiers
# (These remain part of the current Execution Slice until we refactor the runner registry.)
#
CCORE_TASK_RUNNER_VALIDATE_PROJECT = "validate-project"
CCORE_TASK_RUNNER_INSPECT_PROJECT = "inspect-project"
CCORE_TASK_RUNNER_GENERATE_DOCUMENTATION = "generate-documentation"

CCORE_TASK_EXECUTION_DEFAULT_PROVIDER_PROFILE = "prefect"
CCORE_TASK_EXECUTION_DEFAULT_MODE = "manual"
CCORE_TASK_EXECUTION_DEFAULT_REQUESTED_BY = "system"

CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_ID = "executionId"
CCORE_TASK_EXECUTION_API_FIELD_TASK_ID = "taskId"
CCORE_TASK_EXECUTION_API_FIELD_STATUS = "status"
CCORE_TASK_EXECUTION_API_FIELD_STATUS_LABEL = "statusLabel"
CCORE_TASK_EXECUTION_API_FIELD_PROVIDER_PROFILE = "providerProfile"
CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_MODE = "executionMode"
CCORE_TASK_EXECUTION_API_FIELD_REQUESTED_BY = "requestedBy"
CCORE_TASK_EXECUTION_API_FIELD_INPUT_PAYLOAD = "inputPayload"
CCORE_TASK_EXECUTION_API_FIELD_CONFIGURATION_SNAPSHOT = "configurationSnapshot"
CCORE_TASK_EXECUTION_API_FIELD_VALIDATION_SNAPSHOT = "validationSnapshot"
CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_REPORT = "executionReport"
CCORE_TASK_EXECUTION_API_FIELD_ERROR_DETAILS = "errorDetails"
CCORE_TASK_EXECUTION_API_FIELD_STARTED_AT = "startedAt"
CCORE_TASK_EXECUTION_API_FIELD_COMPLETED_AT = "completedAt"
CCORE_TASK_EXECUTION_API_FIELD_FAILED_AT = "failedAt"
CCORE_TASK_EXECUTION_API_FIELD_CREATED_AT = "createdAt"
CCORE_TASK_EXECUTION_API_FIELD_UPDATED_AT = "updatedAt"
