"""
CCore task execution constants.

Responsibilities:
- Centralize CCore task execution table, column, status ID, and API field names.
- Keep execution runtime metadata names out of services/routes.
- Avoid hardcoded execution contract strings across repositories, services, and routes.
"""

CCORE_TASK_EXECUTION_STATUSES_TABLE_NAME = "ccore_task_execution_statuses"
CCORE_TASK_EXECUTION_PROVIDERS_TABLE_NAME = "ccore_execution_providers"
CCORE_TASK_EXECUTION_IMPLEMENTER_TYPES_TABLE_NAME = "ccore_execution_implementer_types"
CCORE_TASK_EXECUTION_TARGETS_TABLE_NAME = "ccore_execution_targets"
CCORE_TASK_EXECUTION_CONFIGURATIONS_TABLE_NAME = "ccore_execution_configurations"
CCORE_TASK_EXECUTION_CONFIGURATION_ELEMENTS_TABLE_NAME = "ccore_execution_configuration_elements"
CCORE_TASK_EXECUTIONS_TABLE_NAME = "ccore_task_executions"

CCORE_TASK_EXECUTION_STATUS_ID_COLUMN = "execution_status_id"
CCORE_TASK_EXECUTION_STATUS_LABEL_COLUMN = "status_label"
CCORE_TASK_EXECUTION_STATUS_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_PROVIDER_ID_COLUMN = "execution_provider_id"
CCORE_TASK_EXECUTION_PROVIDER_LABEL_COLUMN = "provider_label"
CCORE_TASK_EXECUTION_PROVIDER_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_IMPLEMENTER_TYPE_ID_COLUMN = "execution_implementer_type_id"
CCORE_TASK_EXECUTION_IMPLEMENTER_TYPE_LABEL_COLUMN = "implementer_type_label"
CCORE_TASK_EXECUTION_IMPLEMENTER_TYPE_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_TARGET_ID_COLUMN = "execution_target_id"
CCORE_TASK_EXECUTION_TARGET_LABEL_COLUMN = "target_label"
CCORE_TASK_EXECUTION_TARGET_REFERENCE_COLUMN = "target_reference"
CCORE_TASK_EXECUTION_TARGET_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_CONFIGURATION_ID_COLUMN = "execution_configuration_id"
CCORE_TASK_EXECUTION_CONFIGURATION_LABEL_COLUMN = "configuration_label"
CCORE_TASK_EXECUTION_CONFIGURATION_DESCRIPTION_COLUMN = "configuration_description"
CCORE_TASK_EXECUTION_CONFIGURATION_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_CONFIGURATION_ELEMENT_ID_COLUMN = "execution_configuration_element_id"
CCORE_TASK_EXECUTION_CONFIGURATION_ELEMENT_NAME_COLUMN = "element_name"
CCORE_TASK_EXECUTION_CONFIGURATION_ELEMENT_VALUE_COLUMN = "element_value"
CCORE_TASK_EXECUTION_CONFIGURATION_ELEMENT_SORT_ORDER_COLUMN = "sort_order"

CCORE_TASK_EXECUTION_ID_COLUMN = "execution_id"
CCORE_TASK_EXECUTION_TASK_ID_COLUMN = "task_id"
CCORE_TASK_EXECUTION_REQUESTED_BY_COLUMN = "requested_by"
CCORE_TASK_EXECUTION_INPUT_PAYLOAD_COLUMN = "input_payload"
CCORE_TASK_EXECUTION_CONFIGURATION_SNAPSHOT_COLUMN = "configuration_snapshot"
CCORE_TASK_EXECUTION_VALIDATION_SNAPSHOT_COLUMN = "validation_snapshot"
CCORE_TASK_EXECUTION_REPORT_COLUMN = "execution_report"
CCORE_TASK_EXECUTION_ERROR_DETAILS_COLUMN = "error_details"
CCORE_TASK_EXECUTION_STARTED_AT_COLUMN = "started_at"
CCORE_TASK_EXECUTION_COMPLETED_AT_COLUMN = "completed_at"
CCORE_TASK_EXECUTION_FAILED_AT_COLUMN = "failed_at"
CCORE_TASK_EXECUTION_CREATED_AT_COLUMN = "created_at"
CCORE_TASK_EXECUTION_UPDATED_AT_COLUMN = "updated_at"

CCORE_TASK_EXECUTION_STATUS_ID_PENDING = 1
CCORE_TASK_EXECUTION_STATUS_ID_RUNNING = 2
CCORE_TASK_EXECUTION_STATUS_ID_COMPLETED = 3
CCORE_TASK_EXECUTION_STATUS_ID_FAILED = 4
CCORE_TASK_EXECUTION_STATUS_ID_BLOCKED = 5

CCORE_TASK_EXECUTION_STATUS_LABEL_COMPLETED = "COMPLETED"
CCORE_TASK_EXECUTION_STATUS_LABEL_FAILED = "FAILED"
CCORE_TASK_EXECUTION_STATUS_LABEL_BLOCKED = "BLOCKED"

CCORE_TASK_EXECUTION_DEFAULT_PROVIDER_ID = 1
CCORE_TASK_EXECUTION_DEFAULT_IMPLEMENTER_TYPE_ID = 1
CCORE_TASK_EXECUTION_DEFAULT_TARGET_ID = 1
CCORE_TASK_EXECUTION_DEFAULT_CONFIGURATION_ID = 1
CCORE_TASK_EXECUTION_DEFAULT_REQUESTED_BY = "system"

CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_ID = "executionId"
CCORE_TASK_EXECUTION_API_FIELD_TASK_ID = "taskId"
CCORE_TASK_EXECUTION_API_FIELD_STATUS = "status"
CCORE_TASK_EXECUTION_API_FIELD_STATUS_ID = "statusId"
CCORE_TASK_EXECUTION_API_FIELD_STATUS_LABEL = "statusLabel"
CCORE_TASK_EXECUTION_API_FIELD_PROVIDER_ID = "providerId"
CCORE_TASK_EXECUTION_API_FIELD_PROVIDER_LABEL = "providerLabel"
CCORE_TASK_EXECUTION_API_FIELD_IMPLEMENTER_TYPE_ID = "implementerTypeId"
CCORE_TASK_EXECUTION_API_FIELD_IMPLEMENTER_TYPE_LABEL = "implementerTypeLabel"
CCORE_TASK_EXECUTION_API_FIELD_TARGET_ID = "targetId"
CCORE_TASK_EXECUTION_API_FIELD_TARGET_LABEL = "targetLabel"
CCORE_TASK_EXECUTION_API_FIELD_TARGET_REFERENCE = "targetReference"
CCORE_TASK_EXECUTION_API_FIELD_CONFIGURATION_ID = "configurationId"
CCORE_TASK_EXECUTION_API_FIELD_CONFIGURATION_LABEL = "configurationLabel"
CCORE_TASK_EXECUTION_API_FIELD_CONFIGURATION_DESCRIPTION = "configurationDescription"
CCORE_TASK_EXECUTION_API_FIELD_REQUESTED_BY = "requestedBy"
CCORE_TASK_EXECUTION_API_FIELD_INPUT_PAYLOAD = "inputPayload"
CCORE_TASK_EXECUTION_API_FIELD_CONFIGURATION_SNAPSHOT = "configurationSnapshot"
CCORE_TASK_EXECUTION_API_FIELD_VALIDATION_SNAPSHOT = "validationSnapshot"
CCORE_TASK_EXECUTION_API_FIELD_EXECUTION_REPORT = "executionReport"
CCORE_TASK_EXECUTION_API_FIELD_ERROR_DETAILS = "errorDetails"
CCORE_TASK_EXECUTION_API_FIELD_STARTED_AT = "startedAt"
CCORE_TASK_EXECUTION_API_FIELD_COMPLETED_AT = "completedAt"
CCORE_TASK_EXECUTION_API_FIELD_FAILED_AT = "failedAt"
CCORE_TASK_EXECUTION_API_FIELD_CREATED_AT = "createdAt"
CCORE_TASK_EXECUTION_API_FIELD_UPDATED_AT = "updatedAt"
